// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1hs9ZzbPP2ejTcXfnnJlTxIioWfnXe3c',
    appId: '1:640778470963:android:565ec0a4bd75951e95c546',
    messagingSenderId: '640778470963',
    projectId: 'seminarkurs-lernapp',
    storageBucket: 'seminarkurs-lernapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1hs9ZzbPP2ejTcXfnnJlTxIioWfnXe3c',
    appId: '1:640778470963:ios:dba4d6a7ef56f72495c546',
    messagingSenderId: '640778470963',
    projectId: 'seminarkurs-lernapp',
    storageBucket: 'seminarkurs-lernapp.firebasestorage.app',
    iosBundleId: 'de.mvlgym.slam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hs9ZzbPP2ejTcXfnnJlTxIioWfnXe3c',
    appId: '1:640778470963:web:54acf822f40ce62595c546',
    messagingSenderId: '640778470963',
    projectId: 'seminarkurs-lernapp',
    authDomain: 'seminarkurs-lernapp.firebaseapp.com',
    storageBucket: 'seminarkurs-lernapp.firebasestorage.app',
  );

}